[catalog.spicetify]
name = "Spicetify"
category = "audio"

[templates.spicetify]
input_path = "spicetify.ini"
output_path = "$XDG_CONFIG_HOME/spicetify/Themes/Comfy/color.ini"
post_hook = "bash '{{ config_dir }}/apply.sh'"
